передача инпута для паны

diff --git a/.github/workflows/publish_to_pub.yml b/.github/workflows/publish_to_pub.yml
--- a/.github/workflows/publish_to_pub.yml
+++ b/.github/workflows/publish_to_pub.yml
@@ -3,7 +3,6 @@ name: "Publish to pub.dev"
 env:
   PUBSPEC_PATH: './pubspec.yaml'
   CHANGELOG_PATH: './CHANGELOG.md'
-#  PANA_TOTAL: '80'
 
 on:
   workflow_call:
@@ -20,74 +19,74 @@ on:
         required: true
 
 jobs:
-#  check_versions:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v2
-#
-#      - name: Get tag
-#        run: |
-#          echo "TAG=$(git describe --tags --abbrev=0 --exact-match --match 'v*' HEAD | cut -c 2-)" >> $GITHUB_ENV
-#
-#      - name: Tag is empty
-#        if: ${{ env.TAG == ''}}
-#        uses: actions/github-script@v6
-#        with:
-#          script: |
-#            core.setFailed('Tag not found!')
-#
-#      - name: Echo tag
-#        run: |
-#          echo "TAG: ${{ env.TAG }}"
-#
-#      - name: Get pubspec version
-#        run: |
-#          echo "PUBSPEC_VERSION=$(cat $PUBSPEC_PATH | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs)" >> $GITHUB_ENV
-#
-#      - name: Pubspec version is empty
-#        if: ${{ env.PUBSPEC_VERSION == ''}}
-#        uses: actions/github-script@v6
-#        with:
-#          script: |
-#            core.setFailed('Pubspec version not found!')
-#
-#      - name: Echo pubspec version
-#        run: |
-#          echo "Pubspec version: ${{ env.PUBSPEC_VERSION }}"
-#
-#      - name: Get changelog version
-#        run: |
-#          echo "CHANGELOG_VERSION=$(cat $CHANGELOG_PATH | grep -o '## [^:]*' -m '1' | cut -c '4-' | xargs)" >> $GITHUB_ENV
-#
-#      - name: Changelog version is empty
-#        if: ${{ env.CHANGELOG_VERSION == ''}}
-#        uses: actions/github-script@v6
-#        with:
-#          script: |
-#            core.setFailed('Changelog version not found!')
-#
-#      - name: Echo changelog version
-#        run: |
-#          echo "Changelog version: ${{ env.CHANGELOG_VERSION }}"
-#
-#      - name: Compare versions failed
-#        if: "!contains(env.PUBSPEC_VERSION, env.TAG) && !contains(env.CHANGELOG_VERSION, env.TAG)"
-#        run: |
-#          echo "TAG: ${{ env.TAG }}"
-#          echo "CHANGELOG: ${{ env.CHANGELOG_VERSION }}"
-#          echo "PUBSPEC: ${{ env.PUBSPEC_VERSION }}"
-#          echo "::error::The versions don't match!"
-#          exit 1
-#
-#      - name: Compare versions succes
-#        run: |
-#          echo "TAG: ${{ env.TAG }}"
-#          echo "CHANGELOG: ${{ env.CHANGELOG_VERSION }}"
-#          echo "PUBSPEC: ${{ env.PUBSPEC_VERSION }}"
+  check_versions:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Get tag
+        run: |
+          echo "TAG=$(git describe --tags --abbrev=0 --exact-match --match 'v*' HEAD | cut -c 2-)" >> $GITHUB_ENV
+
+      - name: Tag is empty
+        if: ${{ env.TAG == ''}}
+        uses: actions/github-script@v6
+        with:
+          script: |
+            core.setFailed('Tag not found!')
+
+      - name: Echo tag
+        run: |
+          echo "TAG: ${{ env.TAG }}"
+
+      - name: Get pubspec version
+        run: |
+          echo "PUBSPEC_VERSION=$(cat $PUBSPEC_PATH | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs)" >> $GITHUB_ENV
+
+      - name: Pubspec version is empty
+        if: ${{ env.PUBSPEC_VERSION == ''}}
+        uses: actions/github-script@v6
+        with:
+          script: |
+            core.setFailed('Pubspec version not found!')
+
+      - name: Echo pubspec version
+        run: |
+          echo "Pubspec version: ${{ env.PUBSPEC_VERSION }}"
+
+      - name: Get changelog version
+        run: |
+          echo "CHANGELOG_VERSION=$(cat $CHANGELOG_PATH | grep -o '## [^:]*' -m '1' | cut -c '4-' | xargs)" >> $GITHUB_ENV
+
+      - name: Changelog version is empty
+        if: ${{ env.CHANGELOG_VERSION == ''}}
+        uses: actions/github-script@v6
+        with:
+          script: |
+            core.setFailed('Changelog version not found!')
+
+      - name: Echo changelog version
+        run: |
+          echo "Changelog version: ${{ env.CHANGELOG_VERSION }}"
+
+      - name: Compare versions failed
+        if: "!contains(env.PUBSPEC_VERSION, env.TAG) && !contains(env.CHANGELOG_VERSION, env.TAG)"
+        run: |
+          echo "TAG: ${{ env.TAG }}"
+          echo "CHANGELOG: ${{ env.CHANGELOG_VERSION }}"
+          echo "PUBSPEC: ${{ env.PUBSPEC_VERSION }}"
+          echo "::error::The versions don't match!"
+          exit 1
+
+      - name: Compare versions succes
+        run: |
+          echo "TAG: ${{ env.TAG }}"
+          echo "CHANGELOG: ${{ env.CHANGELOG_VERSION }}"
+          echo "PUBSPEC: ${{ env.PUBSPEC_VERSION }}"
 
   pana:
-#    needs: check_versions
+    needs: check_versions
     runs-on: ubuntu-latest
     steps:
       - name: Set up Repository
@@ -117,18 +116,18 @@ jobs:
           if [ -z "$1" ]; then MINIMUM_SCORE=${{ inputs.PANA_TOTAL }}; else MINIMUM_SCORE=$1; fi
           if (( $SCORE < $MINIMUM_SCORE )); then echo "Minimum score $MINIMUM_SCORE was not met!"; exit 1; fi
 
-#  package-publishing:
-#    needs: [ check_versions, pana ]
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: 'Checkout'
-#        uses: actions/checkout@v2
-#
-#      - name: '>> Flutter package <<'
-#        uses: k-paxian/dart-package-publisher@master
-#        with:
-#          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
-#          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
-#          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
-#          flutter: true
-#          dryRunOnly: false
+  package-publishing:
+    needs: [ check_versions, pana ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'Checkout'
+        uses: actions/checkout@v2
+
+      - name: '>> Flutter package <<'
+        uses: k-paxian/dart-package-publisher@master
+        with:
+          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
+          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
+          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
+          flutter: true
+          dryRunOnly: false
